use_frameworks!

platform :ios, '8.0'

target 'TLMImageTestSecond_Example' do
  pod 'TLMImageTestSecond', :path => '../'

  target 'TLMImageTestSecond_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
